# ==> Ansible Role for start Admin Server for the first time in a configured
# ==> WebLogic 12c R2 Domain
- name: Create security folder on Admin Server
  file: state=directory path={{ domains_home }}/{{ domain_name }}/servers/{{ admin_server_name }}/security owner={{ oracle_user }} group={{ oracle_group }}   mode=0755 recurse=yes 
  tags:
    - start-admin-server
- name: Create boot.properties file
  template: src=boot.properties dest={{ domains_home }}/{{ domain_name }}/servers/{{ admin_server_name }}/security/ owner={{ oracle_user }} group={{ oracle_group }} 
  tags:
    - start-admin-server
    
- name: Change permission and ownership to domain directory
  file:
    path: '{{ oracle_base }}'
    owner: '{{ oracle_user }}'
    group: '{{ oracle_group }}'
    mode: '0755'
    recurse: yes
    state: directory

- name: Start WebLogic Admin Server
  shell: "nohup sh {{ domains_home }}/{{ domain_name }}/bin/startWebLogic.sh > /tmp/startWebLogic.log 2>&1 &"
  become: yes
  become_user: "{{ oracle_user }}"
    #register: start_server
    
- name: sleep for a specified interval
  command: sleep '{{ sleep_interval }}'

