---
- name: Configure Oracle Linux  with WebLogic 12c R2 domain
  hosts: server
# connection: local
  become: yes
  become_method: sudo
  vars_files:
    # User defined variables for infrastructure
    - infra-vars.yml
    # Common properties. You may not delete this
    - wls-vars.yml
    # Infrastructure passwords
    - secrets.yml
  roles:
    - role: linux-wls
      #when: weblogic_install
    - role: linux-jdk
      #when: weblogic_install
    - role: fmw-software
      sudo_user: '{{ oracle_user }}'
      #when: weblogic_install
    - role: fmw-domain
      sudo_user: '{{ oracle_user }}'
      #when: weblogic_install
    - role: node-manager
     #when: weblogic_install
    - role: start-admin-server
      sudo_user: '{{ oracle_user }}'
      #when: weblogic_install
 #   - role: fmw-managed-server
 #     sudo_user: '{{ oracle_user }}'
      #when: weblogic_install
      #   - role: app-deployment
      #tags: deploy
      #when: app_deplyment_flag
 # pre_tasks:
    # ==> Fix hosts file. Remove hostname from local loop. A workaround for
    # remove hostname to local loop
   # - name: fix host file 127.0.0.1 entry
   #   lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644
