- name: Recursively remove App deployment directory
  file:
    path: "{{ mw_deployment_folder }}"
    state: absent

- name: Create Application folder on Admin Server
  file: state=directory path={{ mw_deployment_folder }} owner={{ oracle_user }} group={{ oracle_group }}

#- name: Copy Admin Server start-up script
#  template: src=start-admin-server.py dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }} mode=0755
#  tags:
#    - start-admin-server

- name: Copy the deployment files 
 # become: yes
  #become_user: weblogic
  #tags: cpscripts
  copy:
     src: "{{ item }}"
     dest: "{{ mw_deployment_folder }}"
     #mode: 0755
  with_items:
    - "appdeployment.py"
    - "deployment_config.txt"
    - "sample.war"
    - "sample_2.war"


- name: Start App Deployment
  shell: "{{ middleware_common_home }}/common/bin/wlst.sh {{ mw_deployment_folder }}/appdeployment.py"
  #async: 1000
  #poll: 0
